import Link from "next/link";

export default function Home() {
  return (
    <div className="flex flex-col flex-1 items-center justify-center min-h-screen bg-zinc-50 dark:bg-zinc-950 font-sans px-4">
      <main className="flex flex-col items-center gap-10 w-full max-w-2xl py-20">
        <div className="flex flex-col items-center gap-4 text-center">
          <h1 className="text-4xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
            AI Support Agent
          </h1>
          <p className="max-w-lg text-lg leading-7 text-zinc-500 dark:text-zinc-400">
            A side-by-side playground for evaluating AI responses using two
            different frameworks: AI SDK structured output scoring and
            LangSmith tracing with feedback.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 w-full">
          <Link
            href="/api/ui/stream"
            className="group flex flex-col gap-3 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm transition-all hover:shadow-md hover:border-zinc-300 dark:hover:border-zinc-700"
          >
            <div className="flex items-center gap-2">
              <span className="inline-flex items-center rounded-full bg-blue-100 dark:bg-blue-950 px-2.5 py-0.5 text-xs font-medium text-blue-700 dark:text-blue-300">
                AI SDK
              </span>
            </div>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
              Structured Output Evaluation
            </h2>
            <p className="text-sm leading-6 text-zinc-500 dark:text-zinc-400">
              Chat with the model and evaluate responses using AI SDK&apos;s
              structured output with Zod schema validation. Scores are
              generated by an LLM-as-judge pipeline entirely within the app.
            </p>
            <span className="mt-auto text-sm font-medium text-blue-600 dark:text-blue-400">
              Open chat →
            </span>
          </Link>

          <Link
            href="/api/ui/langsmith"
            className="group flex flex-col gap-3 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm transition-all hover:shadow-md hover:border-zinc-300 dark:hover:border-zinc-700"
          >
            <div className="flex items-center gap-2">
              <span className="inline-flex items-center rounded-full bg-emerald-100 dark:bg-emerald-950 px-2.5 py-0.5 text-xs font-medium text-emerald-700 dark:text-emerald-300">
                LangSmith
              </span>
            </div>
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50 group-hover:text-emerald-600 dark:group-hover:text-emerald-400 transition-colors">
              LangSmith Traced Evaluation
            </h2>
            <p className="text-sm leading-6 text-zinc-500 dark:text-zinc-400">
              Chat with the model while every run is traced and scored via
              LangSmith. Evaluation feedback is attached to the parent run so
              you can review it directly in the LangSmith dashboard.
            </p>
            <span className="mt-auto text-sm font-medium text-emerald-600 dark:text-emerald-400">
              Open chat →
            </span>
          </Link>
        </div>
      </main>
    </div>
  );
}
